# Generated by Django 3.0.6 on 2020-05-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location_address', models.CharField(max_length=250)),
                ('public', models.BooleanField()),
                ('lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=250)),
                ('spot_public', models.BooleanField()),
                ('spot_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('spot_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('spot_date', models.DateField(auto_now_add=True)),
                ('spot_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=250)),
                ('trail_public', models.BooleanField()),
                ('trail_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('trail_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('trail_date', models.DateField(auto_now_add=True)),
                ('trail_spot', models.ManyToManyField(to='trail_app.Spot')),
            ],
        ),
    ]
