# Generated by Django 3.0.6 on 2020-06-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
