# Generated by Django 3.0.6 on 2020-06-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0002_auto_20200604_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_address',
            new_name='address',
        ),
    ]
