# Generated by Django 3.0.6 on 2020-10-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0003_auto_20200609_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='trail_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail_app.Location'),
        ),
    ]
