# Generated by Django 3.0.6 on 2021-02-11 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0004_trail_trail_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='trail_spot',
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_on_trail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail_app.Trail'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail_app.Location'),
        ),
        migrations.CreateModel(
            name='Trail_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_name', models.CharField(max_length=250)),
                ('tg_start_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('tg_start_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('tg_end_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('tg_end_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('tg_public', models.BooleanField()),
                ('tg_date', models.DateTimeField(auto_now_add=True)),
                ('tg_end', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_end', to='trail_app.Location')),
                ('tg_start', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_start', to='trail_app.Location')),
            ],
        ),
    ]
