# Generated by Django 3.0.6 on 2021-02-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0006_auto_20210212_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_spots',
            field=models.ManyToManyField(blank=True, to='trail_app.Spot'),
        ),
    ]
