# Generated by Django 3.0.6 on 2021-02-23 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trail_app', '0007_auto_20210216_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trail',
            name='trail_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trail_group',
            name='tg_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
